kind: Job
apiVersion: batch/v1
metadata:
  name: zhu-mnist-gpu-test-$BUILD_NUMBER
  namespace: $PROJECT_NAMESPACE
spec:
  #backoffLimit: 5
  template:
    spec:
      initContainers:
      - name: prepare-dataset
        # hub.data.wust.edu.cn:30880/ygtao/mnist-dataset:v1.0
        image: $DATASET_IMAGE
        command: ['sh', '-c', 'mv /dataset/* /tempdir;echo the init container is used to prepare dataset for your code!']
        volumeMounts:
        - name: shared-dataset
          mountPath: /tempdir
      containers:
        - name: zhu-mnist-gpu-test-$BUILD_NUMBER
          image: hub.data.wust.edu.cn:30880/zhu/zhu-mnist-gpu-test:$BUILD_NUMBER
          volumeMounts:
          - name: shared-dataset
            mountPath: /dataset
          resources:
            limits:
              nvidia.com/gpu: 1
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
       - name: $HARBOR_LOGIN_SECRET_NAME
      restartPolicy: Never
      volumes:
      - name: shared-dataset
        emptyDir: {}