kind: Job
apiVersion: batch/v1
metadata:
  name: zhu-docunet-$BUILD_NUMBER
  namespace: $PROJECT_NAMESPACE
spec:
  #backoffLimit: 5
  template:
    spec:
      containers:
        - name: base #$APP_NAME-$BUILD_NUMBER
          image: hub.data.wust.edu.cn:30880/zhu/zhu-docunet:$BUILD_NUMBER
          resources:
            limits:
              nvidia.com/gpu: 1
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
       - name: $HARBOR_LOGIN_SECRET_NAME
      restartPolicy: Never